---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    groups:
      pip:
        patterns:
          - "*"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: weekly
